### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by kazimuth** [getsentry/milksnake#4]
I'd like to use this tool for a project, but the project requires Windows support. I'm curious how far out Windows support is, and what work needs to be done to support Windows.

**Comment by anthrotype** [comment]
I tried to compile the provided example using Windows with python 3.6 and latest rust (msvc toolchain).

The only problems I found so far are:

1) the `spec.find_dylib` fails to find the compiled DLL because it always prefixes it with "lib" (whereas on windows DLL built with msvc the "lib" prefix is usually omitted) and the library extension is either ".dylib" (mac) or ".so", whereas on windows is ".dll" of course

2) the `rtld_flags` in the example's setup.py contains `RTLD_NODELETE`, which doesn't work on windows (commenting it out, works)

3) linking the fake extension module fails with "unresolved external symbol PyInit__native__lib"; so for Windows the hack of building the "empty.c" extension module doesn't work; it needs to actually export something.

Other than that, everything seems to work. It should be relatively simple to fix theses.
I can send some PR when I find some time, if you like.

**Comment by filmor** [comment]
I concluded exactly the same: https://github.com/getsentry/milksnake/pull/7

**Comment by mitsuhiko** [comment]
I merged #7 now but I wonder what the best solution for the nodelete is for rust users.

**Comment by filmor** [comment]
What do you need it for? As far as I see it, the `dlopen`ed lib is kept alive for as long as the module is kept alive.

**Comment by mitsuhiko** [comment]
@filmor maybe it's indeed not necessary on windows. On mac we get crashes in rust libraries on interpreter shutdown because rust registers TLS dtors which are not executed on lib unload.

**Comment by filmor** [comment]
If you can give me a test case I can check.

**Comment by anthrotype** [comment]
> maybe it's indeed not necessary on windows

according to the cffi docs, the `flags` argument is ignored on Windows

> For the optional flags argument, see man dlopen (ignored on Windows).

https://cffi.readthedocs.io/en/latest/cdef.html#ffi-dlopen-loading-libraries-in-abi-mode

Perhaps you could leave `rtld_flags` empty when `sys.platform == "win32"`?

**Comment by anthrotype** [comment]
oh, that's what #7 already does, sorry for the noise.

**Comment by theotherjimmy** [comment]
It looks like master supports Windows. Could we have '0.1.2' with windows support please?

**Comment by theotherjimmy** [comment]
@mitsuhiko Thanks for releasing 0.1.2! We now have windows support. I'll submit a PR to update the README shortly.

EDIT: Done. See #11

**Comment by theotherjimmy** [comment]
I take it back: Windows Wheels don't contain the `.dll` file.

EDIT: This is true, but not a problem. There is a `.pyd` file that apparently contains the `.dll`!?

**Comment by filmor** [comment]
The pyd *is* the DLL.

**Comment by theotherjimmy** [comment]
@filmor Yeah, that became clear after a bit of testing!

**Comment by mitsuhiko** [comment]
Closing this as this should work now.
